#azure-pipelines.yml
trigger: 
- "*"

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: CmdLine@2
  inputs:
    script: "git clone https://github.com/jasontangontario/mslearn-tailspin-spacegame-web.git $(System.DefaultWorkingDirectory)/mslearn-tailspin-spacegame-web"

- task: UseYuniqlCLI@1
  inputs:
    version: "v1.1.55"
    
- task: RunYuniqlCLI@1
  inputs:
    version: "v1.1.55"
    connectionString: "Host=postgres-migration-poc.postgres.database.azure.com;Port=5432;Username=mtoadmin@postgres-migration-poc;Password=Password123$;Database=postgres;ssl=required"  
    workspacePath: "$(System.DefaultWorkingDirectory)/mslearn-tailspin-spacegame-web/yuniql"
    additionalArguments: "--debug"
