trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:

#set variables
  - bash: |
    echo "##vso[task.setvariable variable=sauce]crushed tomatoes"
    echo "##vso[task.setvariable variable=secretSauce;issecret=true]crushed tomatoes with garlic"
    echo "##vso[task.setvariable variable=outputSauce;isoutput=true]canned goods"
  name: SetVars
