pool:
  vmImage: 'ubuntu-16.04'
steps:
- bash: echo "Hello world"
- bash: echo ${{Pipeline.workspace}}
- bash: echo ${{Agent.BuildDirectory}}
- bash: echo ${{Build.SourcesDirectory}}
- bash: echo ${{Build.ArtifactStagingDirectory}}
- bash: echo ${{Build.BinariesDirectory}}
- bash: echo ${{Common.TestResultsDirectory}}