#azure-pipelines.yml
trigger: 
-build-agent

pool:
  vmImage:'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'git clone https://github.com/jasontangontario/mslearn-tailspin-spacegame-web.git $(Build.SourceDirectory)/mslearn-tailspin-spacegame-web'

- task: UseYunialCLI@1
  inputs:
    version: 'v1.1.55'
    
- task: RunYunialCLI@1
  inputs:
    version: 'v1.1.55'
    connectionString: "Host=postgres-migration-poc.postgres.database.azure.com;Port=5432;Username=mtoadmin@postgres-migration-poc;Password=Password123$;Database=postgres;ssl=required"  
    workspacePath: "$(Build.SourceDirectory)/mslearn-tailspin-spacegame-web/yuniql"
    additionalArguments: '--debug'
