#azure-pipelines.yml
trigger: 
- "*"

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "Hello world"

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: drop
